#!/usr/bin/env python3
"""Independent Python binary64 ESTA oracle; never imports the C++ implementation.

Generate a small frozen C++ fixture and a JSONL exchange file for MATLAB.
Inputs are dyadic binary32 values; nu remains exactly representable for this
sequence. sqrt/output/mapping are evaluated independently in Python binary64.
"""
import argparse
import json
import math
from pathlib import Path


def samples():
    gains = [(2.75, 1.75, 0.5), (4.25, 3.5, 2.5), (1.5, 0.625, 7.0)]
    nu = [0.375, -0.625, 1.25]
    for k in range(96):
        axis = k % 3
        rate = ((k * 37) % 129 - 64) / 16
        sp = ((k * 17) % 33 - 16) / 32
        if k % 11 == 0:
            rate = sp
        dt = [1 / 512, 1 / 256, 1 / 128][(k // 3) % 3]
        l1, l2, g = gains[axis]
        s = rate - sp
        sign = (s > 0) - (s < 0)
        old = nu[axis]
        a = old - l1 * math.copysign(math.sqrt(abs(s)), s) if s else old
        nu[axis] = old - dt * l2 * sign
        yield dict(axis=axis, rate=rate, sp=sp, dt=dt, lambda1=l1,
                   lambda2=l2, g=g, nu_old=old, s=s, a=a, c=a / g,
                   nu_next=nu[axis])


def fixture():
    lines = ['// Generated by research/sta-rate-control/scripts/reference_m02.py.',
             '// Python binary64 oracle, not C++ or MATLAB execution.',
             '#pragma once',
             'struct ReferenceSample {',
             '\tunsigned axis;',
             '\tfloat rate, sp, dt, lambda1, lambda2, g;',
             '\tdouble nu_old, s, a, c, nu_next;',
             '};', 'static constexpr ReferenceSample reference_samples[] = {']
    for row in samples():
        floats = ', '.join(repr(row[key]) + 'f' for key in
                           ('rate', 'sp', 'dt', 'lambda1', 'lambda2', 'g'))
        doubles = ', '.join(repr(row[key]) for key in
                            ('nu_old', 's', 'a', 'c', 'nu_next'))
        lines.append('\t{' + str(row['axis']) + ', ' + floats + ', ' + doubles + '},')
    return '\n'.join(lines + ['};', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, help='Generate the fixture at this path')
    parser.add_argument('--check', type=Path, help='Require byte-identical existing fixture')
    parser.add_argument('--jsonl', type=Path, help='Write optional MATLAB exchange data')
    args = parser.parse_args()
    if args.output:
        args.output.write_text(fixture())
    if args.check:
        if args.check.read_text() != fixture():
            raise SystemExit('FAIL: frozen oracle fixture differs')
        print('PASS: 96 frozen binary64 samples regenerated exactly')
    if args.jsonl:
        args.jsonl.write_text(''.join(json.dumps(row) + '\n' for row in samples()))


if __name__ == '__main__':
    main()
